export const credits = [
  {
    id: 1,
    name: {
      uz: `"National Green"`,
      ru: `"National Green"`,
    },
    logo: "nbu",
    interest: 20,
    payment: 0,
    duration: { from: 0, to: 60 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 60000000,
    info: [
      { uz: "Kredit stavkasi - yillik 20%", ru: "Кредитная ставка - ежегодная 20%" },
      { uz: "Kredit miqdori 60 mln so'mgacha", ru: "Кредитная сумма 60 млн. сум" },
      { uz: "Kredit muddati - 5 yil", ru: "Срок кредита - 5 лет" },
    ],
    link: "https://nbu.uz/jismoniy-shaxslarga-kreditlar/national-green",
  },
  {
    id: 2,
    name: {
      uz: `"Tomorqa textnikasi" krediti`,
      ru: `Tomorqa texnikasi`,
    },
    logo: "sqb",
    interest: 25,
    payment: 0,
    duration: { from: 0, to: 36 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 40000000,
    info: [
      { uz: "Kredit foiz stavkasi 25%", ru: "Кредитная ставка 25%" },
      { uz: "Kredit miqdori 40 mln so'mgacha", ru: "Кредитная сумма до 40 млн. сум" },
      { uz: "Kredit muddati - 36 oygacha", ru: "Срок кредита - до 36 месецев" },
    ],
    link: "https://sqb.uz/uz/individuals/credits/tomorqa-texnikasi-uz/",
  },
  {
    id: 3,
    name: {
      uz: `Eksportoldi moliyalashtirish`,
      ru: `Предэкспортное финансирование`,
    },
    logo: "asakabank",
    interest: 27,
    payment: 0,
    duration: { from: 0, to: 12 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: null,
    info: [
      { uz: "Kredit foiz stavkasi 27%", ru: "Кредитная ставка 27%" },
      { uz: "Kredit muddati - 12 oygacha", ru: "Срок кредита - до 12 месецев" },
    ],
    link: "https://www.asakabank.uz/uz/corporate-customers/home",
  },
  {
    id: 5,
    name: {
      uz: `"Yashil energiya" yurudik va jismoniy shaxslar uchun`,
      ru: `"Yashil energiya" для физ. и юр. лиц`,
    },
    logo: "agrobank",
    interest: 19.5,
    payment: 0,
    duration: { from: 0, to: 60 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 100000000,
    info: [
      { uz: "Kredit foiz stavkasi 19.5%", ru: "Кредитная ставка 19.5%" },
      { uz: "Kredit miqdori 100 mln so'mgacha", ru: "Кредитная сумма до 100 млн. сум" },
      { uz: "Muddati - 60 oy (imtiyozli davr - 6 oy)", ru: "Срок - 60 месяцев (льготный период - 6 месяцев)" },
    ],
    link: "https://agrobank.uz/uz/business/loans/green-energy-b2b",
  },
  {
    id: 6,
    name: {
      uz: `MFSR-diversifikatsiya kredit liniyasi`,
      ru: `Кредитная линия МФСР-диверсификация`,
    },
    logo: "xalqbanki",
    interest: 19,
    payment: 0,
    duration: { from: 0, to: 120 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 6500000000,
    info: [
      { uz: "Kredit foizi - 19%", ru: "Процентная ставка - 19%" },
      { uz: "Kredit summasi 6,5 mlrd so'mgacha", ru: "Сумма кредита - до 6,5 млрд. сум" },
      { uz: "Kredit muddati - 120 oygacha", ru: "Срок кредита - до 120 месяцев" },
    ],
    link: "https://xb.uz/page/mfsr-diversifikatsiya-kredit-liniyasi",
  },
  {
    id: 8,
    name: {
      uz: `"Chorvachilikni rivojlantirish" krediti`,
      ru: `Кредит «Развитие животноводства»`,
    },
    logo: "brb",
    interest: 21,
    payment: 0,
    duration: { from: 0, to: 120 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 1298400000,
    info: [
      { uz: "Yillik foiz stavkasi 19%", ru: "Ежегодная ставка 19%" },
      { uz: "Kredit miqdori - 13.5 mlrd. so'mgacha", ru: "Кредитная Сумма - до 13,5 млрд. сум" },
      {
        uz: "Muddati - Investitsiya loyihalari uchun – 120 oygacha;	Aylanma mablag‘lar uchun – 18 oygacha",
        ru: "Срок - до 120 месяцев для инвестиционных проектов; до 18 месяцев для вложений",
      },
    ],
    link: "https://brb.uz/kreditlar/chorvachilikni-rivojlantirish-krediti",
  },
  {
    id: 9,
    name: {
      uz: `"Oʻzbekiston Respublikasi qishloq xoʻjaligini diversifikatsiya va modernizatsiya qilish” loyihasi (IFAD)`,
      ru: `Проект «Диверсификация и модернизация сельского хозяйства Республики Узбекистан» (МФСР)`,
    },
    logo: "mkbank",
    interest: 10,
    payment: 0,
    duration: { from: 0, to: 120 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 4546487855,
    info: [
      { uz: "Foiz stavkasi 10% dan", ru: "Ставка от 10%" },
      { uz: "Kredit miqdori - 350 min AQSH dollari", ru: "Кредитная сумма - до 350 долларов США" },
      { uz: "Muddati - 10 yilgacha", ru: "Срок - до 10 лет" },
    ],
    link: "https://mkbank.uz/uz/corporate/crediting/ifadmoder/",
  },
  {
    id: 10,
    name: {
      uz: `“Green energy”`,
      ru: `“Green energy”`,
    },
    logo: "mkbank",
    interest: 20.5,
    payment: 0,
    duration: { from: 0, to: 60 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 5000000000,
    info: [
      { uz: "Foiz stavkasi 20.5%", ru: "Ставка 20.5%" },
      { uz: "Kredit miqdori - 5 mlrd so'mgacha", ru: "Кредитная сумма - до 5 млрд. сум" },
      { uz: "Muddati - 60 oygacha", ru: "Срок - до 60 месяцев" },
    ],
    link: "https://mkbank.uz/uz/corporate/crediting/green-energy-3469/",
  },
  {
    id: 12,
    name: {
      uz: `“IMKONIYAT” krediti`,
      ru: `Кредит “IMKONIYAT”`,
    },
    logo: "mkbank",
    interest: 19,
    payment: 0,
    duration: { from: 0, to: 84 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 300000000,
    info: [
      { uz: "Foiz stavkasi 19% dan", ru: "Ставка от 19%" },
      { uz: "Kredit miqdori - 300 mln. so’mgacha", ru: "Кредитная сумма - до 300 млн. сум" },
      { uz: "Muddati - 84 oygacha", ru: "Срок - до 84 месяцев" },
    ],
    link: "https://mkbank.uz/uz/corporate/crediting/imkoniyat-kredit/",
  },
  {
    id: 13,
    name: {
      uz: `Qishloq xo‘jaligini rivojlantirish uchun`,
      ru: `Qishloq xo‘jaligini rivojlantirish uchun`,
    },
    logo: "mkbank",
    interest: 25,
    payment: 0,
    duration: { from: 0, to: 60 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: null,
    info: [
      { uz: "Foiz stavkasi 25% dan", ru: "Ставка от 25%" },
      { uz: "Kredit miqdori - loyiha qiymatidan", ru: "Сумма кредита - от стоимости проекта" },
      { uz: "Muddati - 60 oygacha", ru: "Срок - до 60 месяцев" },
    ],
    link: "https://mkbank.uz/uz/corporate/crediting/qishloq-xo-jaligini-rivojlantirish-uchun/",
  },
  {
    id: 14,
    name: {
      uz: `Mikrokredit`,
      ru: `Mikrokredit`,
    },
    logo: "aloqabank",
    interest: 4,
    payment: 0,
    duration: { from: 0, to: 36 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 340000000,
    info: [
      { uz: "Yillik foiz stavkasi - 19%", ru: "Ежегодная ставка - 19%" },
      { uz: "Kredit miqdori - 340 mln. so’mgacha", ru: "Кредитная сумма - до 340 млн. сум" },
      { uz: "Muddati - 3 yilgacha", ru: "Срок - до 3 лет" },
    ],
    link: "https://aloqabank.uz/uz/corporate/crediting/microloan-passport/",
  },
  {
    id: 15,
    name: {
      uz: `«Muqobil Energiya uchun» modulli krediti`,
      ru: `«Muqobil Energiya uchun» modulli krediti`,
    },
    logo: "aloqabank",
    interest: 20.5,
    payment: 0,
    duration: { from: 0, to: 36 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 1500000000,
    info: [
      { uz: "Yillik foiz stavkasi - 20.5% dan", ru: "Ежегодная ставка от 20.5%" },
      { uz: "Kredit miqdori - 1,5 mlrd. so’mgacha", ru: "Кредитная сумма - до 1,5 млрд. сум" },
      { uz: "Muddati - 36 oygacha", ru: "Срок - до 36 месяцев" },
    ],
    link: "https://aloqabank.uz/uz/corporate/crediting/muqobil-energiya-modulli-krediti/",
  },
  {
    id: 17,
    name: {
      uz: `ECOPANEL`,
      ru: `ECOPANEL`,
    },
    logo: "turonbank",
    interest: 20.5,
    payment: 0,
    duration: { from: 0, to: 60 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: null,
    info: [
      { uz: "Foiz stavkasi - 20,5% gacha", ru: "Cтавка - до 20,5%" },
      { uz: "Kredit miqdori - Shartnomaga asosan", ru: "Кредитная сумма - в соответствии с договором" },
      { uz: "Muddati - 60 oygacha", ru: "Срок - до 60 месяцев" },
    ],
    link: "https://turonbank.uz/uz/corporate/crediting/ecopanel/",
  },
];
